### ISSUE TITLE
create or update standard models populates yml files in the models folder

### ISSUE THREAD

**Issue by Frydafly** [bsd/dbt-arc-functions#114]
@ryantimjohn create or update standard models.py now populates all of the yml files with the same name alongside the sql files and places them in the models folder instead of in the documentation folder.

**Comment by Frydafly** [comment]
it also doesn't fully populate all of the sql models inside of the folders anymore

**Comment by Frydafly** [comment]
here's an image of the error I get 
![Uploading Screenshot 2022-11-03 at 2.54.23 PM.png…]()

and here you can see only one file will populate bc it expects there to also be yml files

<img width="332" alt="Screenshot 2022-11-03 at 2 55 59 PM" src="https://user-images.githubusercontent.com/22733009/199821324-8ea5fefb-baab-494f-8961-16cb7d3f984f.png">

what I imagine is happening is I am required to create documentation yml files in order for create or update standard models to run?

**Comment by Frydafly** [comment]
and.... that is correct! Ok, I'm going to close this issue bc it's not a bug in the code but it took me a little to realize I would have to create documentation yml files that match the sql models in order for this to work

if we can add documentation to dbt arc functions relating this info, that would be good!

**Comment by ryantimjohn** [comment]
Makes sense... could even add it to the PR checklist you have!

**Comment by Frydafly** [comment]
Oh of course! Yes yes
