### ISSUE TITLE
create_or_update_standard_models issue

### ISSUE THREAD

**Issue by Frydafly** [bsd/dbt-arc-functions#115]
the util now copies all of the sql and documentation yml files and dumps them in the models folder, rather than placing the yml documentation files in the documentation folder.

**Comment by ryantimjohn** [comment]
ooooo.... not good

**Comment by ryantimjohn** [comment]
I was about to be like... oh no, but wait, that's intended behavior? Will reach out directly @Frydafly

**Comment by Frydafly** [comment]
solved by https://github.com/bsd/dbt-arc-functions/pull/118
