### ISSUE TITLE
Change display of models in create_or_update_standard_models to alphabetical order?

### ISSUE THREAD

**Issue by Frydafly** [bsd/dbt-arc-functions#135]
When create_or_update_standard_models asks me which models I'd like to update, I'd like to see it in alphabetical order. we have SO MANY now, it'll be easier to understand that way

@ryantimjohn, if you have the capacity to make the adjustment, otherwise I'll add to my backlog!

**Comment by ryantimjohn** [comment]
https://bluestate.atlassian.net/browse/ARC-1230
