### ISSUE TITLE
generate dbt documentation site hosted in GitHub.io? 

### ISSUE THREAD

**Issue by Frydafly** [bsd/dbt-arc-functions#146]
and link to that site in dbt arc functions? that would be such an amazing way to have macro documentation directly connected to this GitHub. 

example: [dbt_artifacts dbt package](https://github.com/brooklyn-data/dbt_artifacts) links to their dbt macros documentation site on their repo, and it seems to be hosted in GitHub.io [their dbt documentation site](https://brooklyn-data.github.io/dbt_artifacts/#!/overview)

**Comment by bsd-analytics** [comment]
Link to issue in JIRA
https://bluestate.atlassian.net/browse/ARC-1249

**Comment by Frydafly** [comment]
is it this? https://github.com/dbt-labs/dbt-docs hmm

**Comment by Frydafly** [comment]
CLOSING -- we are working on a notion site instead, documented in JIRA
