### ISSUE TITLE
Add sqlfmt to pipfile

### ISSUE THREAD

**Issue by dmbluestate** [bsd/dbt-arc-functions#209]
https://github.com/bsd/dbt-arc-functions/blob/4ab0114fa9c7485a55134d96d44e9d81f5e51f00/utils/Pipfile#L6

**Comment by bsd-analytics** [comment]
Link to issue in JIRA
https://bluestate.atlassian.net/browse/ARC-1434

**Comment by dmbluestate** [comment]
add other linter packages import to (python, sql, yml) to pipfile as well to ensure that everyone uses the same dialect when testing.
