### ISSUE TITLE
Audience YOY -- change this so that it looks at any donation made before a certain date to account for the 3rd year. rather than having to look up 3 years ago and 4 years ago.

### ISSUE THREAD

**Issue by Frydafly** [bsd/dbt-arc-functions#212]
change retained 3+ query in you so that it looks at any donation made before a certain date to account for the 3rd year. rather than having to look up 3 years ago and 4 years ago.

_Originally posted by @Frydafly in https://github.com/bsd/dbt-arc-functions/pull/201#discussion_r1177039405_

**Comment by bsd-analytics** [comment]
Link to issue in JIRA
https://bluestate.atlassian.net/browse/ARC-1444

**Comment by Frydafly** [comment]
done
