### ISSUE TITLE
Add a line that outputs that no all macros have docs when run on a repo that has all macros documented

### ISSUE THREAD

**Issue by dmbluestate** [bsd/dbt-arc-functions#244]
https://github.com/bsd/dbt-arc-functions/blob/356e6c03e3eb509a7ad4592fd7ef6884df119b49/utils/check_for_docs_for_every_macro.py#L7

**Comment by bsd-analytics** [comment]
Link to issue in JIRA
https://bluestate.atlassian.net/browse/ARC-1505
