### ISSUE TITLE
When compiling, return two keys in dictionary. (see photo)

### ISSUE THREAD

**Issue by dmbluestate** [bsd/dbt-arc-functions#270]
https://github.com/bsd/dbt-arc-functions/blob/ce4386cbe00cf5387138934aa82deefc2ec04c57/documentation/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_customizable_audience_transaction_jobs_append.yml#L18-L25

<img width="912" alt="Screenshot 2023-07-19 at 11 37 14 AM" src="https://github.com/bsd/dbt-arc-functions/assets/109629735/bae1d503-1952-481f-b80a-dfc14657fd1b">

**Comment by bsd-analytics** [comment]
Link to issue in JIRA
https://bluestate.atlassian.net/browse/ARC-1548
