### ISSUE TITLE
Calculated Donor_audience Logic Bug

### ISSUE THREAD

**Issue by dmbluestate** [bsd/dbt-arc-functions#308]
https://github.com/bsd/dbt-arc-functions/blob/36e401a17ad18061de80fca311774a1a0c940177/macros/stitch_sfmc_audience_transaction/staging/stg_stitch_sfmc_audience_transaction_jobs_append.sql#L12

This logic produces errors in the calculated assignment of donor_audiences and needs further investigation.

**Comment by bsd-analytics** [comment]
Link to issue in JIRA
https://bluestate.atlassian.net/browse/ARC-1593

**Comment by Frydafly** [comment]
resolved with https://github.com/bsd/dbt-arc-functions/pull/358
